<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Verify.TUnit" />
    <PackageReference Include="TUnit" />
    <PackageReference Include="Argon" />
    <PackageReference Include="DiffEngine" />
    <PackageReference Include="EmptyFiles" />
    <PackageReference Include="SimpleInfoName" />
    <PackageReference Include="Verify" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <ProjectReference Include="..\Verify.OpenXml\Verify.OpenXml.csproj" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />

    <None Include="..\Verify.OpenXml.Tests\sample.xlsx" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\Verify.OpenXml.Tests\sample.docx" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
